---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bundle-unpacker
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bundle-unpacker
  namespace: system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bundle-unpacker
rules:
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - bundles
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bundle-unpacker
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bundle-unpacker
subjects:
  - kind: ServiceAccount
    name: bundle-unpacker
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bundle-unpacker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bundle-unpacker
subjects:
  - kind: ServiceAccount
    name: bundle-unpacker
    namespace: system
