---
apiVersion: olm.operatorframework.io/v1alpha1
kind: Bundle
metadata:
  name: memcached-api-0.1.0
spec:
  image: quay.io/joelanford/memcached-api-bundle:v0.1.0
  provisionerClassName: kuberpak.io/plain+v1
---
apiVersion: olm.operatorframework.io/v1alpha1
kind: Bundle
metadata:
  name: memcached-api-0.2.0
spec:
  image: quay.io/joelanford/memcached-api-bundle:v0.2.0
  provisionerClassName: kuberpak.io/plain+v1
